# Generated by Django 5.1.6 on 2025-03-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="custom_prompt",
            field=models.TextField(
                blank=True,
                help_text="Пользовательский запрос для анализа документов. Оставьте пустым для использования стандартного промпта.",
                null=True,
            ),
        ),
    ]
