# Generated by Django 5.1.6 on 2025-03-02 20:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0002_analysis_custom_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата завершения"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="custom_prompt",
            field=models.TextField(
                blank=True,
                help_text="Пользовательский запрос для анализа документов. Оставьте пустым для использования стандартного промпта.",
                null=True,
                verbose_name="Пользовательский запрос",
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="documents",
            field=models.ManyToManyField(
                related_name="analyses", to="agent.document", verbose_name="Документы"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="result",
            field=models.TextField(blank=True, null=True, verbose_name="Результат"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("processing", "В процессе"),
                    ("completed", "Завершен"),
                    ("failed", "Не удалось"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="documents/", verbose_name="Файл"),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(max_length=50, verbose_name="Тип файла"),
        ),
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата загрузки"),
        ),
    ]
