# Generated by Django 5.1.6 on 2025-03-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0003_alter_analysis_completed_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysis",
            options={"verbose_name": "Анализ", "verbose_name_plural": "Анализы"},
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "Документ", "verbose_name_plural": "Документы"},
        ),
    ]
